[project]
name = "meet-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.135.2",
    "flask>=3.1.3",
    "google-adk>=1.28.0",
    "python-dotenv>=1.1.1",
    "scalekit-sdk-python>=2.6.1",
    "streamlit>=1.55.0",
    "websocket-client>=1.9.0",
    "websockets>=15.0.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "pages*"]
